services:
  web:
    image: pamelaiwabuchi/unitev:v4
    build: .
    ports:
      - "5000:5000"
    environment:
      # Se não encontrar variável, assume o valor local do container 'db'
      MYSQLHOST: ${MYSQLHOST:-db}
      MYSQLPORT: ${MYSQLPORT:-3306}
      MYSQLUSER: ${MYSQLUSER:-root}
      MYSQLPASSWORD: ${MYSQLPASSWORD:-sua_senha_aqui}
      MYSQLDATABASE: ${MYSQLDATABASE:-universidade_unitev}
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD:-sua_senha_aqui}
      MYSQL_DATABASE: ${MYSQLDATABASE:-universidade_unitev}
    ports:
      - "3306:3306"